version: "3"

services:
  telegram-bot:
    container_name: fuel-parser-bot
    build: .

    environment:
      FPB_BOT_TOKEN: ${FPB_BOT_TOKEN}
      FPB_BOT_ADMIN: ${FPB_BOT_ADMIN}
      FPB_REDIS_IP: redis-server

    volumes:
      - ./data:/opt/fuel_scraping_bot/data

    networks:
      - network

    depends_on:
      - redis-server

  redis-server:
    container_name: redis-server
    image: redis

    volumes:
      - redis-data:/var/lib/redis

    networks:
      - network

volumes:
  redis-data:

networks:
  network: