version: "3"

services:
  telegram-bot:
    container_name: fuel-parser-bot
    build: .

    environment:
      FPB_BOT_TOKEN: ${FPB_BOT_TOKEN}
      FPB_BOT_ADMIN: ${FPB_BOT_ADMIN}

    depends_on:
      - redis-server

  redis-server:
    container_name: redis-server
    image: redis

    volumes:
      - redis-data:/var/lib/redis

volumes:
  redis-data: